"""The `itemiset` command: a file of sets in, a figure out.

Docs: https://adamcc.github.io/itemiset/cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_cli.ipynb.

# %% auto #0
__all__ = ['run', 'main']

# %% ../nbs/03_cli.ipynb #cb0844b9
import argparse
import sys
from pathlib import Path

from . import __version__
from .readers import load_sets
from .render import plot

# %% ../nbs/03_cli.ipynb #a7ac832c
def _parser():
    ap = argparse.ArgumentParser(
        prog="itemiset",
        description="Draw an itemized area-proportional Euler diagram: one cell per item, so area is count.")
    ap.add_argument("input", help="CSV, TSV or Excel file: a membership table, or one column per set")
    ap.add_argument("-o", "--out", default=None, help="output .png, .pdf or .svg (default: <input>_itemiset.png)")
    ap.add_argument("--sheet", default=None, help="Excel sheet with the sets (default: the first sheet)")
    ap.add_argument("--sets", default=None,
                    help="comma-separated set columns to use, in colour order (cyan, magenta, yellow)")
    ap.add_argument("--categories", default=None, help="file with columns gene, category[, color]")
    ap.add_argument("--categories-sheet", default=None, help="sheet of the categories file to read")
    ap.add_argument("--category-colors", default=None, help='for example "Decapping=#C8102E,CCR4-NOT=#2140A8"')
    ap.add_argument("--bottom", default=None, help="set to place along the bottom (3 sets only)")
    ap.add_argument("--show-empty", action="store_true", help="draw each empty zone as one ∅ cell")
    ap.add_argument("--title", default=None, help="title above the diagram")
    ap.add_argument("--aspect", type=float, default=2.2, help="target width-to-height ratio (default 2.2)")
    ap.add_argument("--fontsize", type=float, default=6.5, help="font size of the names in points")
    ap.add_argument("--no-outline", action="store_true", help="don't draw set outlines")
    ap.add_argument("--zones-out", default=None, help="also write a CSV of each item and its zone")
    ap.add_argument("--version", action="version", version=f"itemiset {__version__}")
    return ap

# %% ../nbs/03_cli.ipynb #a5f23f00
def run(argv=None):
    "Run the `itemiset` command with `argv` (default: the command-line arguments) and return the `Layout` it drew."
    ap = _parser()
    a = ap.parse_args(argv)
    sets, cats, ccols = load_sets(a.input, a.sheet, a.categories, a.categories_sheet)
    if a.sets:
        wanted = [s.strip() for s in a.sets.split(",")]
        missing = [s for s in wanted if s not in sets]
        if missing:
            ap.error(f"unknown set(s) {missing}; the file has {list(sets)}")
        sets = {s: sets[s] for s in wanted}
    if a.category_colors:
        for kv in a.category_colors.split(","):
            k, v = kv.rsplit("=", 1)
            ccols[k.strip()] = v.strip()
    out = a.out or str(Path(a.input).with_suffix("")) + "_itemiset.png"
    return plot(sets, out=out, categories=cats, category_colours=ccols, show_empty=a.show_empty,
                bottom=a.bottom, title=a.title, target_aspect=a.aspect, fontsize=a.fontsize,
                zones_out=a.zones_out, verbose=True, outline=not a.no_outline)

def main(argv=None):
    "Entry point for the `itemiset` command. Returns nothing, so the command exits with status 0."
    run(argv)
