"""Real, published proximity-labelling hits to try ItemiSet on.

Docs: https://adamcc.github.io/itemiset/examples.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_examples.ipynb.

# %% auto #0
__all__ = ['load_example']

# %% ../nbs/05_examples.ipynb #b8d15b22
import json
from importlib.resources import files

# %% ../nbs/05_examples.ipynb #21855427
def load_example(name: str = "pbody") -> dict:
    "Load a bundled example: a dict with `sets`, `categories`, `category_colours`, `scores` and text describing it."
    data = json.loads(files("itemiset").joinpath("data/examples.json").read_text(encoding="utf-8"))
    if name not in data:
        raise KeyError(f"No example called {name!r}; choose from {sorted(data)}")
    ex = data[name]
    return {**ex, "sets": {k: v for k, v in ex["sets"]}}
