"""Read sets from CSV, TSV and Excel files.

Docs: https://adamcc.github.io/itemiset/readers.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_readers.ipynb.

# %% auto #0
__all__ = ['TRUTHY', 'ID_COLS', 'EXCEL_SUFFIXES', 'load_sets']

# %% ../nbs/01_readers.ipynb #7f56cdf0
import csv
import math
from pathlib import Path

import pandas as pd

# %% ../nbs/01_readers.ipynb #4f0bff99
TRUTHY = {"1", "1.0", "y", "yes", "true", "t", "x", "+", "✓"}
ID_COLS = ("gene", "genes", "id", "name", "protein", "prey", "item", "symbol")
EXCEL_SUFFIXES = (".xlsx", ".xlsm", ".xls")

def _sniff_sep(path, default):
    "Comma, tab or semicolon, whichever the file uses; `default` if it has only one column."
    with open(path, encoding="utf-8-sig", newline="") as f:
        sample = f.read(64 * 1024)
    try:
        return csv.Sniffer().sniff(sample, delimiters=",\t;").delimiter
    except csv.Error:
        return default

def _read_table(path, sheet=None):
    path = Path(path)
    suf = path.suffix.lower()
    if suf in EXCEL_SUFFIXES:
        return pd.read_excel(path, sheet_name=sheet if sheet is not None else 0, dtype=str)
    sep = _sniff_sep(path, "\t" if suf in (".tsv", ".tab") else ",")
    return pd.read_csv(path, sep=sep, dtype=str, encoding="utf-8-sig")

def _clean(x):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return ""
    return str(x).strip()

# %% ../nbs/01_readers.ipynb #2578182c
def load_sets(path, sheet=None, categories_path=None, categories_sheet=None):
    "Read sets from `path`. Returns (sets: {name: [items]}, categories: {item: category}, category colours: {category: colour})."
    df = _read_table(path, sheet)
    df.columns = [str(c).strip() for c in df.columns]
    df = df.loc[:, [c for c in df.columns if not c.lower().startswith("unnamed")]]
    lower = {c.lower(): c for c in df.columns}
    categories, cat_colours = {}, {}

    id_col = next((lower[k] for k in ID_COLS if k in lower), None)
    if id_col is not None:                                   # membership table
        cat_col = lower.get("category") or lower.get("group") or lower.get("class")
        col_col = lower.get("color") or lower.get("colour")
        set_cols = [c for c in df.columns if c not in (id_col, cat_col, col_col)]
        sets = {s: [] for s in set_cols}
        for _, row in df.iterrows():
            item = _clean(row[id_col])
            if not item:
                continue
            for s in set_cols:
                if _clean(row[s]).lower() in TRUTHY:
                    sets[s].append(item)
            if cat_col and _clean(row[cat_col]):
                categories[item] = _clean(row[cat_col])
                if col_col and _clean(row[col_col]):
                    cat_colours[categories[item]] = _clean(row[col_col])
    else:                                                    # one column per set
        sets = {c: [v for v in (_clean(x) for x in df[c]) if v] for c in df.columns}

    # categories from a separate file, or from a 'categories' sheet of the same workbook
    cpath, csheet = categories_path, categories_sheet
    if cpath is None and Path(path).suffix.lower() in EXCEL_SUFFIXES:
        names = pd.ExcelFile(path).sheet_names
        hit = next((n for n in names if n.strip().lower() in ("categories", "category")), None)
        if hit:
            cpath, csheet = path, hit
    if cpath is not None:
        cdf = _read_table(cpath, csheet)
        cl = {str(c).strip().lower(): c for c in cdf.columns}
        gcol = next((cl[k] for k in ID_COLS if k in cl), cdf.columns[0])
        ccol = cl.get("category", cdf.columns[1])
        kcol = cl.get("color") or cl.get("colour")
        for _, row in cdf.iterrows():
            g, c = _clean(row[gcol]), _clean(row[ccol])
            if g and c:
                categories[g] = c
                if kcol and _clean(row[kcol]):
                    cat_colours[c] = _clean(row[kcol])

    sets = {k: list(dict.fromkeys(v)) for k, v in sets.items()}   # drop duplicates, keep order
    if not 1 <= len(sets) <= 3:
        raise ValueError(f"Need 1 to 3 sets, found {len(sets)}: {list(sets)}")
    return sets, categories, cat_colours
